import { generateImage } from "@/server/agents/generate";
import { agentPersonas } from "@/server/agents/personas";
import { getGeminiClient } from "@/server/agents/gemini-client";
import type { SampleEvaluation, IntentWeights } from "@/types/audit";
import type { ImageAgentId } from "@/types/agent";
import type { Content, Part } from "@google/genai";

// Generate images from all 3 agents in parallel
export async function generateAllSamples(
  taskDescription: string,
): Promise<SampleEvaluation[]> {
  const results = await Promise.all(
    agentPersonas.map(async (persona) => {
      try {
        const result = await generateImage(
          persona.id as ImageAgentId,
          taskDescription,
        );
        const dataUrl = `data:${result.mimeType};base64,${result.imageBase64}`;
        return {
          id: `sample-${persona.id}`,
          agentId: persona.id,
          agentName: persona.name,
          model: `Gemini 3.1 Flash (${persona.style})`,
          score: 0,
          recommendation: result.textResponse || `Generated by ${persona.name}`,
          sampleTitle: `${persona.style} — Sample`,
          summary: result.textResponse || `Image generated in ${persona.style} style.`,
          imageDataUrl: dataUrl,
        } satisfies SampleEvaluation;
      } catch (err) {
        return {
          id: `sample-${persona.id}`,
          agentId: persona.id,
          agentName: persona.name,
          model: `Gemini 3.1 Flash (${persona.style})`,
          score: 0,
          recommendation: `Generation failed: ${err instanceof Error ? err.message : "unknown error"}`,
          sampleTitle: `${persona.style} — Failed`,
          summary: "Image generation did not succeed for this agent.",
        } satisfies SampleEvaluation;
      }
    }),
  );

  return results;
}

// LLM judge: comparative scoring of samples using Gemini
export async function llmJudgeScore(
  samples: SampleEvaluation[],
  taskDescription: string,
  weights: IntentWeights,
): Promise<SampleEvaluation[]> {
  const client = getGeminiClient();

  const parts: Part[] = [
    {
      text: `You are an impartial judge evaluating AI-generated image samples.

Task requested: "${taskDescription}"

Scoring criteria weights:
- Visual quality: ${Math.round(weights.quality * 100)}%
- Value for price: ${Math.round(weights.price * 100)}%
- Speed/efficiency: ${Math.round(weights.speed * 100)}%

Below are ${samples.length} samples. For each, provide:
1. A score from 0.00 to 1.00 (weighted by the criteria above)
2. A one-sentence recommendation explaining your score

Return ONLY valid JSON, no markdown fencing:
[{"agentId": "...", "score": 0.XX, "recommendation": "..."}]

Samples:`,
    },
  ];

  for (const sample of samples) {
    parts.push({
      text: `\n--- ${sample.agentName} (${sample.agentId}) ---\nStyle: ${sample.model}\nDescription: ${sample.summary}`,
    });

    if (sample.imageDataUrl) {
      const match = sample.imageDataUrl.match(/^data:(.+?);base64,(.+)$/);
      if (match) {
        parts.push({ inlineData: { mimeType: match[1], data: match[2] } });
      }
    }
  }

  const contents: Content[] = [{ role: "user", parts }];

  const response = await client.models.generateContent({
    model: "gemini-3-flash-preview",
    contents,
  });

  const text = response.text ?? "";
  const jsonMatch = text.match(/\[[\s\S]*?\]/);
  if (!jsonMatch) return samples;

  try {
    const scores = JSON.parse(jsonMatch[0]) as Array<{
      agentId: string;
      score: number;
      recommendation: string;
    }>;

    return samples
      .map((sample) => {
        const entry = scores.find((s) => s.agentId === sample.agentId);
        if (!entry) return sample;
        return {
          ...sample,
          score: Math.max(0, Math.min(1, entry.score)),
          recommendation: entry.recommendation || sample.recommendation,
        };
      })
      .sort((a, b) => b.score - a.score);
  } catch {
    return samples;
  }
}
