import { generateImage } from "@/server/agents/generate";
import { getPersona } from "@/server/agents/personas";
import type { ImageAgentId } from "@/types/agent";
import type { SampleEvaluation } from "@/types/audit";
import type { ApiError } from "@/types/audit";

export const runtime = "nodejs";
export const maxDuration = 60;

export async function POST(
  request: Request,
  { params }: { params: Promise<{ agentId: string }> },
): Promise<Response> {
  const { agentId } = await params;

  const persona = getPersona(agentId);
  if (!persona) {
    return Response.json(
      { error: `Unknown agent: ${agentId}` } satisfies ApiError,
      { status: 404 },
    );
  }

  let body: { prompt?: string } = {};
  try {
    body = await request.json();
  } catch {
    return Response.json(
      { error: "Invalid JSON" } satisfies ApiError,
      { status: 400 },
    );
  }

  const prompt = body.prompt;
  if (!prompt) {
    return Response.json(
      { error: "prompt is required" } satisfies ApiError,
      { status: 400 },
    );
  }

  try {
    const result = await generateImage(agentId as ImageAgentId, prompt);
    const dataUrl = `data:${result.mimeType};base64,${result.imageBase64}`;

    const sample: SampleEvaluation = {
      id: `sample-${agentId}`,
      agentId,
      agentName: persona.name,
      model: `Gemini 3.1 Flash (${persona.style})`,
      score: 0,
      recommendation: result.textResponse || `Generated by ${persona.name}`,
      sampleTitle: `${persona.style} — Sample`,
      summary: result.textResponse || `Image generated in ${persona.style} style.`,
      imageDataUrl: dataUrl,
    };

    return Response.json(sample);
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Image generation failed";
    return Response.json(
      { error: message } satisfies ApiError,
      { status: 500 },
    );
  }
}
