import { generateImage } from "@/server/agents/generate";
import { getPersona } from "@/server/agents/personas";
import type { AgentTaskKind, ImageAgentId } from "@/types/agent";
import type { SampleEvaluation } from "@/types/audit";
import type { ApiError } from "@/types/audit";

export const runtime = "nodejs";
export const maxDuration = 60;

export async function POST(
  request: Request,
  { params }: { params: Promise<{ agentId: string }> },
): Promise<Response> {
  const { agentId } = await params;

  const persona = getPersona(agentId);
  if (!persona) {
    return Response.json(
      { error: `Unknown agent: ${agentId}` } satisfies ApiError,
      { status: 404 },
    );
  }

  let body: { prompt?: string } = {};
  try {
    body = await request.json();
  } catch {
    return Response.json(
      { error: "Invalid JSON" } satisfies ApiError,
      { status: 400 },
    );
  }

  const prompt = body.prompt;
  if (!prompt) {
    return Response.json(
      { error: "prompt is required" } satisfies ApiError,
      { status: 400 },
    );
  }

  try {
    const result = await generateImage(agentId as ImageAgentId, prompt, {
      phase: "sample",
    });
    const taskKind = result.taskKind;
    const dataUrl = `data:${result.mimeType};base64,${result.imageBase64}`;
    const recommendation = buildSampleRecommendation(taskKind, persona.name, result.textResponse);
    const summary = buildSampleSummary(taskKind, persona.style, result.textResponse);

    const sample: SampleEvaluation = {
      id: `sample-${agentId}`,
      agentId,
      agentName: persona.name,
      model: `Nano Banana (${persona.style})`,
      score: 0,
      recommendation,
      sampleTitle:
        taskKind === "four-panel-comic"
          ? `${persona.style} — Comic Keyframe Sample`
          : `${persona.style} — Sample`,
      summary,
      imageDataUrl: dataUrl,
      taskKind,
      persona: {
        personality: persona.personality,
        taste: persona.taste,
        skills: persona.skills,
      },
      plan: result.plan,
    };

    return Response.json(sample);
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Image generation failed";
    return Response.json(
      { error: message } satisfies ApiError,
      { status: 500 },
    );
  }
}

function buildSampleRecommendation(
  taskKind: AgentTaskKind,
  agentName: string,
  textResponse: string,
): string {
  if (textResponse.trim()) return textResponse.trim();
  if (taskKind === "four-panel-comic") {
    return `${agentName} provided one keyframe sample and a planned 4-panel delivery flow.`;
  }
  return `Generated by ${agentName}`;
}

function buildSampleSummary(
  taskKind: AgentTaskKind,
  style: string,
  textResponse: string,
): string {
  if (textResponse.trim()) return textResponse.trim();
  if (taskKind === "four-panel-comic") {
    return `Sample stage: one representative comic frame in ${style}. Final delivery should be a full 4-panel comic.`;
  }
  return `Image generated in ${style} style.`;
}
